files:
  interactions: data/interactions.csv
  item_asset: data/item_asset.csv
  item_price: data/item_price.csv
  item_subclass: data/item_subclass.csv
  user_age: data/user_age.csv
  user_region: data/user_region.csv

ials_params:
  emb_size: 100
  reg_coef: 0.01
  n_iter: 15